Add buildx to CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -17,7 +17,7 @@ jobs:
     name: Test Rust Linear Regression Project
     runs-on: ubuntu-latest
     permissions:
-      pull-requests: write    
+      pull-requests: write
 
     defaults:
       run:
@@ -61,3 +61,33 @@ jobs:
           artifact-name: code-coverage-report
           github-token: ${{ secrets.GITHUB_TOKEN }}
           update-comment: true
+
+  build_and_smoke_test_docker_image:
+    name: Build and Smoke Test Docker Image for Rust Linear Regression Project
+    needs: test_rust_linear_regression
+    runs-on: ubuntu-latest
+
+    defaults:
+      run:
+        working-directory: ./rust_projects/linear_regression
+    
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v5
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3      
+      
+      - name: Build and smoke test Docker image
+        run: |
+          version=$(grep -m1 '^version =' Cargo.toml | sed 's/version = "\(.*\)"/\1/')
+          docker build -t linear_regression:"$version" -f docker/Dockerfile .
+          output=$(docker run --rm linear_regression:"$version")
+          if [[ "$output" == *"Usage: linear_regression <input_file> <output_file>"* ]]; then
+            echo "Smoke test passed."
+          else
+            echo "Smoke test failed."
+            exit 1
+          fi
+
+
